language: node_js
node_js:
  - "14"
dist: trusty
sudo: required
branches:
  only:
  - master
before_script:
  - npm install -g @angular/cli
script:
- ng build --prod --base-href https://kapMango.github.io/ci-demo/

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: dist/ci-demo
  on:
    branch: master